/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisesRouteImport } from './routes/analises'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as ContasAReceberRouteImport } from './routes/contas-a-receber'
import { Route as ImportacaoRouteImport } from './routes/importacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesRoute = AnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAReceberRoute = ContasAReceberRouteImport.update({
  id: '/contas-a-receber',
  path: '/contas-a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacaoRoute = ImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/importacao': typeof ImportacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/importacao': typeof ImportacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/importacao': typeof ImportacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analises'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/importacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analises'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/importacao'
  id:
    | '__root__'
    | '/'
    | '/analises'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/importacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisesRoute: typeof AnalisesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  ContasAReceberRoute: typeof ContasAReceberRoute
  ImportacaoRoute: typeof ImportacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises': {
      id: '/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-pagar': {
      id: '/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof ContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-receber': {
      id: '/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/contas-a-receber'
      preLoaderRoute: typeof ContasAReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacao': {
      id: '/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof ImportacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisesRoute: AnalisesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasAPagarRoute: ContasAPagarRoute,
  ContasAReceberRoute: ContasAReceberRoute,
  ImportacaoRoute: ImportacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
